#!/usr/bin/env bash
# Phase 7 — motion, and the hairlines that were not there.
#
#   cd cosign/cosign-app && bash scripts/phase7-evidence.sh
#
# Owns everything it needs: a scratch database (the writing suites below WRITE),
# the built app on $PORT (8787 by default), and its own evidence directory. No
# earlier phase's artifacts are touched.
#
# Do not edit this file while it is running: bash reads a script incrementally
# by byte offset, so an edit mid-run resumes it at a stale position and it dies
# somewhere that has nothing to do with the change. That is what
# `line 94: pair: unbound variable` was.
#
# Unlike Phase 6 this pass CHANGED what the surfaces look like, so the suite
# screenshots are kept rather than deleted: they are the anti-slop review
# artifacts for the design work, and the hairlines are visible in them.
#
# The Lighthouse section is a REGRESSION check, not a new claim. The share page
# gained one animation above the fold (a 1px masthead rule that draws itself)
# and the question is only whether the gate moved. Phase 6's reading of the
# /p/ criterion stands and is unchanged by this pass — see PLAN.md.
#
# `PORT=8791 bash scripts/phase7-evidence.sh` runs the whole pass somewhere
# else. Every tool here already reads `COSIGN_BASE` — the server takes `PORT`,
# playwright.config.ts, lighthouse.mjs and boot-smoke.mjs all take
# `COSIGN_BASE` — but the five earlier scripts hardcode 8787 and simply refuse
# to run when something else has it, which on this machine has meant another
# project's `wrangler dev` (a supervised workerd that respawns the moment you
# kill it). Measuring a phase should not require winning a fight over a port.
set -uo pipefail
cd "$(dirname "$0")/.."
. scripts/lib/server.sh
OUT="../../evidence/phase7"
SCRATCH="${TMPDIR:-/tmp}/cosign-phase7.db"
PORT="${PORT:-8787}"
export PORT
export COSIGN_BASE="http://localhost:$PORT"
mkdir -p "$OUT"

require_free_port "$PORT"

rm -f "$SCRATCH" "$SCRATCH"-shm "$SCRATCH"-wal
COSIGN_DB="$SCRATCH" npm run seed > /tmp/phase7-seed.log 2>&1 || { cat /tmp/phase7-seed.log; exit 1; }
npm run build > /tmp/phase7-build.log 2>&1 || { tail -20 /tmp/phase7-build.log; exit 1; }

COSIGN_DB="$SCRATCH" npm run serve:prod > /tmp/phase7-server.log 2>&1 &
SERVER=$!
trap 'stop_server "$SERVER" "$PORT"' EXIT
wait_for_port "$PORT" || { tail -20 /tmp/phase7-server.log; exit 1; }

# The seeded campus is SHUT between about 02:00 and 06:30 local, and four
# assertions across home.spec and social.spec need somewhere to be open: the
# hero query is "near me, open now, has outlets", and the Open-now chip
# asserts it "matches something in the seed". Run the suite at 06:14 and it
# goes red for a reason that has nothing to do with the code — which is how
# an hour of this pass was spent. Same class as the Phase 6 finding about a
# freshness fixture that stops being true on 2026-10-13; this one expires
# every night. Refuse rather than produce evidence that means nothing.
OPEN=$(curl -s "$COSIGN_BASE/api/discover?lat=40.0067&lng=-83.0305" | node -e "
  let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{
    try{console.log(JSON.parse(s).entries.filter(e=>e.open_now).length)}catch{console.log('0')}});")
if [ "$OPEN" = "0" ]; then
  echo "Nothing in the seed is open at $(date '+%H:%M %Z') — the campus opens at 06:30 on a weekday." >&2
  echo "  Four assertions need an open place; a run now is red for the clock, not the code." >&2
  exit 1
fi

# Seeded tokens (seed/share-tokens.json).
PROFILE=Rp7YT1i9S-Ov      # maya: 22 places
RANKING=IofpCInelhr1      # maya's list — a /s/ token

{
  echo "# Phase 7 evidence — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# node $(node --version), npm $(npm --version)"
  echo "# scratch database: $SCRATCH (server/data/cosign.db untouched)"

  echo; echo "## ./node_modules/.bin/tsc -b"
  ./node_modules/.bin/tsc -b; echo "exit=$?"

  echo; echo "## npm test"
  npm test 2>&1 | grep -E "Test Files|Tests " | sed 's/^/    /'

  echo; echo "## npm run lint"
  npm run lint 2>&1 | grep -E "problem" | sed 's/^/    /'
  echo "    (5 warnings before this pass; four of them were in the deleted shadcn tree)"

  echo; echo "## the motion guard — src/design/motion.test.ts"
  npx vitest run src/design/motion.test.ts 2>&1 | grep -E "✓|×|Tests " | sed 's/^/    /'
  echo "    Its scanner is held by its own fixtures, the way no-scales and no-bait are:"
  echo "    a literal duration in either decimal shape, an \`infinite\`, and an"
  echo "    animation that does not fill \`both\` are each proven to be caught."

  echo; echo "## what the tokens now have to say about stopping"
  echo "\$ grep -A6 'prefers-reduced-motion' src/design/tokens.css"
  grep -A7 "prefers-reduced-motion" src/design/tokens.css | sed 's/^/    /'
  echo "\$ # and every stylesheet carries the BLANKET rule, not a class list:"
  # Parse the block, do not grep near it. `grep -A3` reported index.css as
  # having no universal rule because the selector is spread over three lines
  # there — a transcript that says the opposite of the truth about the thing
  # the phase is about.
  # A 300-character window after the @media, not a parse and not a line
  # count: index.css writes the selector over three lines and the two SSR
  # pages ship the whole query minified onto one, and a check that assumed
  # either shape reported the other as having no rule at all. Twice.
  node -e "
    const fs=require('fs');
    for (const f of ['src/index.css','server/pages/shareList.ts','server/pages/shareProfile.ts']) {
      const src=fs.readFileSync(f,'utf8');
      const at=src.search(/@media\s*\(prefers-reduced-motion:\s*reduce\)/);
      const win=at<0?'':src.slice(at,at+300);
      const ok=at>=0 && /\*\s*[,{]/.test(win)
        && /animation:\s*?none\s*!important/.test(win)
        && /transition:\s*?none\s*!important/.test(win);
      console.log('    '+f.padEnd(32)+(ok
        ? 'universal (*): animation AND transition none !important'
        : 'NOT BLANKET — '+(at>=0?'found the query, but not the universal rule':'no query at all')));
    }"

  echo; echo "## the inline script on the hero surface parses"
  echo "\$ curl -s $COSIGN_BASE/s/$RANKING | <extract the one <script>> | node --check"
  curl -s "$COSIGN_BASE/s/$RANKING" | node -e "
    let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{
      const js=/<script>([\s\S]*?)<\/script>/.exec(s)?.[1]??'';
      console.log('    bytes      : '+js.length);
      console.log('    newlines   : '+(js.split('\n').length-1)+'   (it ships as one joined line)');
      try{new Function(js);console.log('    parses     : yes')}catch(e){console.log('    parses     : NO — '+e.message)}});"
  echo "    (a // comment added inside that literal cost the chips entirely, silently)"

  echo; echo "## the bundle, after the dead tree came out"
  echo "\$ wc -c dist/assets/*"
  for f in dist/assets/*; do printf '    %-30s %8d bytes\n' "$(basename "$f")" "$(wc -c < "$f")"; done
  echo "    before this pass: index.css was 56,483 bytes (gzip 10.3 kB)"
  echo "\$ node -e 'count the dependencies'"
  node -e "const p=require('./package.json');console.log('    dependencies: '+Object.keys(p.dependencies).length+'  ('+Object.keys(p.dependencies).join(', ')+')')"
  echo "    before this pass: 48 dependencies, 38 unused shadcn primitives, and a"
  echo "    \`shimmer 2s linear infinite\` in tailwind.config.ts that nothing could stop."

  echo; echo "## every surface, re-run against this build"
} > "$OUT/commands.txt" 2>&1

# Read-only first, writers last, each into its own directory (CLAUDE.md).
SHARE=$(COSIGN_EVIDENCE=phase7/share-regression npx playwright test share.spec.ts 2>&1 | tail -3)
PROFILE_RUN=$(COSIGN_EVIDENCE=phase7/profile-regression npx playwright test profile.spec.ts 2>&1 | tail -3)
SOCIAL=$(COSIGN_EVIDENCE=phase7/social-regression npx playwright test social.spec.ts 2>&1 | tail -3)
HOME_RUN=$(COSIGN_EVIDENCE=phase7/home npx playwright test home.spec.ts 2>&1 | tail -3)
LOG=$(COSIGN_EVIDENCE=phase7/log-regression npx playwright test log.spec.ts 2>&1 | tail -3)
BOOT=$(COSIGN_EVIDENCE_DIR=phase7/spa node scripts/boot-smoke.mjs 2>&1 | tail -6)

{
  for pair in "share:phase 2" "profile:phase 5A" "social:phase 5B" "home:phase 4 + this pass" "log:phase 3"; do
    name="${pair%%:*}"; phase="${pair##*:}"
    echo "\$ npx playwright test ${name}.spec.ts   # ${phase}"
  done
  echo
  # From each suite's own results JSON, never from the tail of its console
  # output: playwright prints the failure list BETWEEN "N failed" and
  # "N passed", so `tail -3 | grep passed` caught the pass line, missed the
  # fail line, and printed a red run as "42 passed". An evidence script that
  # can hide a failure is worse than no evidence script.
  node -e "
    const fs=require('fs');
    const suites=[['share','share-regression'],['profile','profile-regression'],
                  ['social','social-regression'],['home','home'],['log','log-regression']];
    let bad=0;
    for (const [name,dir] of suites) {
      const p='$OUT/'+dir+'/playwright-results.json';
      if (!fs.existsSync(p)) { console.log('    '+name.padEnd(8)+'NO RESULTS FILE — the suite did not finish'); bad++; continue; }
      const s=JSON.parse(fs.readFileSync(p,'utf8')).stats;
      if (s.unexpected) bad++;
      console.log('    '+name.padEnd(8)+'passed='+String(s.expected).padEnd(4)+
        'failed='+String(s.unexpected).padEnd(4)+'skipped='+String(s.skipped).padEnd(4)+'flaky='+s.flaky);
    }
    console.log('    '+(bad?'>>> '+bad+' suite(s) did not come back clean':'all five suites clean'));"
  echo
  echo "    home.spec.ts gains one test this pass — 'every list column keeps its"
  echo "    hairlines, and only its first row goes without'. Removing the three CSS"
  echo "    rules that fix it and rebuilding makes it fail with [0,0,0,0,0,0]."
  echo
  echo "    Each suite's 'prefers-reduced-motion removes all animation' test walks"
  echo "    every element on the surface and fails on any computed animation- or"
  echo "    transition-duration over 0.01 s. All five pass with the new motion."
  echo
  echo "\$ COSIGN_EVIDENCE_DIR=phase7/spa node scripts/boot-smoke.mjs"
  echo "$BOOT" | sed 's/^/    /'
} >> "$OUT/commands.txt" 2>&1

# ── the gate, as a regression ────────────────────────────────────────────────
GATE_SHARE=$(MSYS_NO_PATHCONV=1 LH_RUNS=5 node scripts/lighthouse.mjs "/s/$RANKING" phase7 share 2>&1)
GS=$?
GATE_PROFILE=$(MSYS_NO_PATHCONV=1 LH_RUNS=5 node scripts/lighthouse.mjs "/p/$PROFILE" phase7 profile 2>&1)
GP=$?

{
  echo; echo "## the perf gate (LCP <= 1000 ms, median of 5, mobile + simulated Slow-4G)"
  echo "\$ LH_RUNS=5 node scripts/lighthouse.mjs /s/$RANKING phase7 share"
  echo "$GATE_SHARE" | grep -E "LCP|performance|runs:" | sed 's/^/    /'
  echo "    gate exit=$GS"
  echo "\$ LH_RUNS=5 node scripts/lighthouse.mjs /p/$PROFILE phase7 profile"
  echo "$GATE_PROFILE" | grep -E "LCP|performance|runs:" | sed 's/^/    /'
  echo "    gate exit=$GP"
  echo
  echo "## what the one added animation costs, measured rather than argued"
  echo "\$ # same build, same server, same URL, back to back: the two .wrap>.kicker"
  echo "\$ # rules removed from server/pages/shareList.ts for the second arm."
  node -e "
    const fs=require('fs');
    const read=(f)=>{const p='$OUT/'+f;return fs.existsSync(p)?JSON.parse(fs.readFileSync(p,'utf8')):null;};
    const a=read('lighthouse-share-control-with-draw.json');
    const b=read('lighthouse-share-control-no-draw.json');
    if(!a||!b){console.log('    (control not present in this directory)');process.exit(0)}
    const spread=(r)=>{const v=r.runs.map(x=>x.lcpMs);return Math.max(...v)-Math.min(...v)};
    console.log('    with the draw   LCP '+a.median.lcpMs+' ms   runs '+a.runs.map(r=>r.lcpMs).join(' ')+'   spread '+spread(a)+' ms');
    console.log('    without it      LCP '+b.median.lcpMs+' ms   runs '+b.runs.map(r=>r.lcpMs).join(' ')+'   spread '+spread(b)+' ms');
    const diff=Math.abs(a.median.lcpMs-b.median.lcpMs);
    const worst=Math.max(spread(a),spread(b));
    // Computed, not written down: an evidence script may not end in a
    // conclusion its own numbers could contradict (Phase 6).
    console.log('    the two medians differ by '+diff+' ms; the widest spread WITHIN one arm is '+
      worst+' ms, i.e. '+Math.round(worst/Math.max(diff,1))+'x the difference between them.');"
  echo
  echo "    This is a regression check on one added animation, not a new reading of"
  echo "    the criterion. Phase 6 measured /s/ at 869 · 911 · 1010 · 833 · 974 ms"
  echo "    across five sessions on bytes that had not changed since Phase 2 — the"
  echo "    gate's own noise is wider than any margin it judges, so a single number"
  echo "    here is one sample of that distribution. What the 1px masthead rule can"
  echo "    cost is bounded by what it is: a composited transform on a hairline that"
  echo "    is not, and cannot become, the largest contentful paint."
} >> "$OUT/commands.txt" 2>&1

echo "wrote $OUT/commands.txt"
tail -45 "$OUT/commands.txt"
