// One-shot seed: rebuilds server/data/cosign.db from the committed sources
// in seed/. Idempotent — deletes and recreates the DB file. Validates
// referential integrity loudly (a bad seed file should fail here, not at
// request time). Comparisons are not hand-authored: they are generated by
// replaying binary-search insertion over each user's ranking arrival order,
// so every ranking is exactly reproducible from its comparison log.

import { existsSync, readFileSync, rmSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { createDb, DB_PATH, APP_ROOT } from "./db.ts";
import { seedHoursToRows } from "../lib/hours.ts";
import { replayInsertion } from "../../src/lib/insertion.ts";
import { semesterForDate, type AcademicCalendar } from "../../src/lib/calendar.ts";
import { INTENT_TAGS } from "../../src/types/cosign.ts";

export const DEFAULT_SEED_DIR = join(APP_ROOT, "seed");
// imagery always lives in the canonical seed dir — exports reference the
// same committed /img paths rather than copying files around
const IMG_DIR = join(DEFAULT_SEED_DIR, "images");

function readJson<T>(dir: string, name: string): T {
  const p = join(dir, name);
  if (!existsSync(p)) throw new Error(`missing seed file: ${p}`);
  return JSON.parse(readFileSync(p, "utf-8")) as T;
}

function fail(msg: string): never {
  throw new Error(`seed validation: ${msg}`);
}

// ── seed file shapes ────────────────────────────────────────────────────────

interface SeedShop {
  id: string; slug: string; name: string; address: string; lat: number; lng: number;
  school: string; price_drip: number; price_latte: number; student_discount: boolean;
  student_discount_note?: string | null;
  last_verified_at: string;
  hours: Array<{ days: number[]; open: string; close: string }>;
  amenities: {
    outlet_count: number | null; outlet_note: string | null; seat_count: number | null;
    table_size: string | null; wifi_mbps: number | null; wifi_note: string | null;
    bathroom_access: string | null; bathroom_code: string | null;
    natural_light: boolean; camp_ok: boolean; camp_note: string | null;
  };
  one_liner: string; palette: string; photos: string[];
}

interface SeedUser {
  id: string; username: string; display_name: string; school: string;
  taste_line: string; signature_order: string; avatar: string; created_at: string;
}

interface SeedFriendship {
  user_id: string; friend_id: string; status: string; created_at: string; responded_at: string | null;
}

interface SeedLog {
  id: string; user_id: string; shop_id: string; intent_tag: string; time_bucket: string;
  created_at: string; noise: string | null; crowd: string | null;
  taps: Record<string, boolean>; photo: string | null; line: string | null; visibility: string;
}

interface SeedList {
  id: string; owner_id: string; title: string; visibility: string; is_collaborative: boolean;
  editors: string[]; items: Array<{ shop_id: string; added_by: string; note?: string }>;
  created_at: string;
}

interface SeedShareToken {
  token: string; kind: string; user_id: string; list_id?: string | null;
  created_at: string; revoked_at: string | null;
}

type SeedRankings = Record<
  string,
  { final: string[]; arrival: string[]; title?: string | null; visibility?: "friends" | "public" }
>;

// ── main ────────────────────────────────────────────────────────────────────

export function runSeed(dbPath: string = DB_PATH, seedDir: string = DEFAULT_SEED_DIR): void {
  const shops = readJson<SeedShop[]>(seedDir, "shops.json");
  const users = readJson<SeedUser[]>(seedDir, "users.json");
  const friendships = readJson<SeedFriendship[]>(seedDir, "friendships.json");
  const logs = readJson<SeedLog[]>(seedDir, "logs.json");
  const lists = readJson<SeedList[]>(seedDir, "lists.json");
  const tokens = readJson<SeedShareToken[]>(seedDir, "share-tokens.json");
  const rankings = readJson<SeedRankings>(seedDir, "rankings.json");
  const calendar = readJson<AcademicCalendar>(seedDir, "academic-calendar.json");

  const shopIds = new Set(shops.map((s) => s.id));
  const userIds = new Set(users.map((u) => u.id));
  const listIds = new Set(lists.map((l) => l.id));

  // ── validation ──
  if (shops.length < 20) fail(`need 20+ shops, got ${shops.length}`);
  if (shopIds.size !== shops.length) fail("duplicate shop ids");
  if (userIds.size !== users.length) fail("duplicate user ids");
  const requireShop = (id: string, where: string) => { if (!shopIds.has(id)) fail(`unknown shop ${id} in ${where}`); };
  const requireUser = (id: string, where: string) => { if (!userIds.has(id)) fail(`unknown user ${id} in ${where}`); };

  for (const [uid, r] of Object.entries(rankings)) {
    requireUser(uid, "rankings.json");
    const fin = [...r.final].sort();
    const arr = [...r.arrival].sort();
    if (JSON.stringify(fin) !== JSON.stringify(arr)) fail(`rankings ${uid}: final/arrival differ as sets`);
    r.final.forEach((s) => requireShop(s, `rankings.json ${uid}`));
    if (new Set(r.final).size !== r.final.length) fail(`rankings ${uid}: duplicate shops`);
  }
  const hero = rankings["u_maya"];
  if (!hero || hero.final.length !== shops.length) {
    fail(`hero u_maya must rank all ${shops.length} shops (has ${hero?.final.length ?? 0})`);
  }
  for (const f of friendships) {
    requireUser(f.user_id, "friendships"); requireUser(f.friend_id, "friendships");
    if (f.user_id === f.friend_id) fail("self-friendship");
  }
  for (const lg of logs) {
    requireUser(lg.user_id, `log ${lg.id}`); requireShop(lg.shop_id, `log ${lg.id}`);
    if (!INTENT_TAGS.includes(lg.intent_tag as never)) fail(`log ${lg.id}: bad intent ${lg.intent_tag}`);
    if (lg.line && lg.line.length > 140) fail(`log ${lg.id}: line > 140 chars`);
    if (lg.photo) {
      const p = join(IMG_DIR, lg.photo.replace("/img/", ""));
      if (!existsSync(p)) fail(`log ${lg.id}: photo missing on disk: ${lg.photo}`);
    }
  }
  for (const t of INTENT_TAGS) {
    if (!logs.some((lg) => lg.intent_tag === t)) fail(`intent tag never used in logs: ${t}`);
  }
  for (const l of lists) {
    requireUser(l.owner_id, `list ${l.id}`);
    l.editors.forEach((e) => requireUser(e, `list ${l.id} editors`));
    l.items.forEach((it) => { requireShop(it.shop_id, `list ${l.id}`); requireUser(it.added_by, `list ${l.id}`); });
  }
  // 3–5 lists per established user. Users with no ranking are the deliberate
  // empty-state fixtures (the brief wants those designed too) and are exempt.
  for (const u of users) {
    if (!rankings[u.id]) continue;
    const owned = lists.filter((l) => l.owner_id === u.id).length;
    if (owned < 3 || owned > 5) fail(`${u.id}: needs 3-5 lists, has ${owned}`);
  }
  const usernames = new Set(users.map((u) => u.username.toLowerCase()));
  for (const t of tokens) {
    requireUser(t.user_id, `token ${t.token}`);
    if (t.kind === "list") {
      if (!t.list_id || !listIds.has(t.list_id)) fail(`token ${t.token}: bad list_id`);
    } else if (t.list_id) {
      fail(`token ${t.token}: only a list token may carry list_id`);
    }
    // Share URLs are unguessable by design (decision 4) — a readable token
    // would quietly restore the username-addressed public page.
    if (!/^[A-Za-z0-9_-]{12,}$/.test(t.token)) fail(`token ${t.token}: must be 12+ url-safe random chars`);
    if (usernames.has(t.token.toLowerCase())) fail(`token ${t.token}: token equals a username`);
  }
  for (const s of shops) {
    for (const kind of s.photos) {
      const p = join(IMG_DIR, "shops", `${s.slug}-${kind}.svg`);
      if (!existsSync(p)) fail(`shop ${s.id}: photo missing on disk: ${s.slug}-${kind}.svg`);
    }
  }
  for (const u of users) {
    const p = join(IMG_DIR, u.avatar.replace("/img/", ""));
    if (!existsSync(p)) fail(`user ${u.id}: avatar missing on disk: ${u.avatar}`);
  }

  // ── build ──
  rmSync(dbPath, { force: true });
  rmSync(dbPath + "-wal", { force: true });
  rmSync(dbPath + "-shm", { force: true });
  const db = createDb(dbPath);
  db.exec("BEGIN");

  const schools = new Set([...users.map((u) => u.school), ...shops.map((s) => s.school)]);
  const insSchool = db.prepare("INSERT INTO schools (id, name) VALUES (?, ?)");
  const SCHOOL_NAMES: Record<string, string> = { osu: "Ohio State University" };
  for (const s of schools) insSchool.run(s, SCHOOL_NAMES[s] ?? s);

  const insUser = db.prepare(
    "INSERT INTO users (id, username, display_name, school_id, avatar, taste_line, signature_order, created_at) VALUES (?,?,?,?,?,?,?,?)",
  );
  for (const u of users) {
    insUser.run(u.id, u.username, u.display_name, u.school, u.avatar, u.taste_line, u.signature_order, u.created_at);
  }

  const insShop = db.prepare(
    "INSERT INTO shops (id, slug, name, address, lat, lng, school_id, price_drip, price_latte, student_discount, student_discount_note, one_liner, palette, last_verified_at, created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
  );
  const insHours = db.prepare("INSERT INTO shop_hours (shop_id, day, open_min, close_min) VALUES (?,?,?,?)");
  const insAmen = db.prepare(
    "INSERT INTO shop_amenities (shop_id, outlet_count, outlet_note, seat_count, table_size, wifi_mbps, wifi_note, bathroom_access, bathroom_code, natural_light, camp_ok, camp_note, updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",
  );
  const insPhoto = db.prepare("INSERT INTO shop_photos (id, shop_id, path, kind, sort) VALUES (?,?,?,?,?)");
  for (const s of shops) {
    insShop.run(
      s.id, s.slug, s.name, s.address, s.lat, s.lng, s.school,
      s.price_drip, s.price_latte, s.student_discount ? 1 : 0,
      s.student_discount_note ?? null,
      s.one_liner, s.palette, s.last_verified_at, "2026-01-05T09:00:00-05:00",
    );
    for (const r of seedHoursToRows(s.hours)) insHours.run(s.id, r.day, r.open_min, r.close_min);
    const a = s.amenities;
    insAmen.run(
      s.id, a.outlet_count, a.outlet_note, a.seat_count, a.table_size, a.wifi_mbps, a.wifi_note,
      a.bathroom_access, a.bathroom_code, a.natural_light ? 1 : 0, a.camp_ok ? 1 : 0, a.camp_note,
      s.last_verified_at,
    );
    s.photos.forEach((kind, i) => {
      insPhoto.run(`ph_${s.slug}_${kind}`, s.id, `/img/shops/${s.slug}-${kind}.svg`, kind, i);
    });
  }

  const insLog = db.prepare(
    "INSERT INTO logs (id, user_id, shop_id, intent_tag, time_bucket, semester, noise, crowd, taps_json, photo, line, visibility, created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",
  );
  for (const lg of logs) {
    const semester = semesterForDate(calendar, new Date(lg.created_at));
    insLog.run(
      lg.id, lg.user_id, lg.shop_id, lg.intent_tag, lg.time_bucket, semester,
      lg.noise, lg.crowd, JSON.stringify(lg.taps ?? {}), lg.photo, lg.line,
      lg.visibility ?? "friends", lg.created_at,
    );
  }

  // Rankings: replay binary-search insertion over the arrival order; the
  // emitted taps become the comparisons table. Timestamps spread one
  // insertion per ~3 days backward from 2026-08-10.
  const insCmp = db.prepare(
    "INSERT INTO comparisons (id, user_id, winner_shop_id, loser_shop_id, context, created_at) VALUES (?,?,?,?,?,?)",
  );
  const insEntry = db.prepare(
    "INSERT INTO ranking_entries (user_id, shop_id, position, inserted_at) VALUES (?,?,?,?)",
  );
  const insRanking = db.prepare(
    "INSERT INTO rankings (user_id, title, visibility, updated_at) VALUES (?,?,?,?)",
  );
  let cmpCount = 0;
  for (const [uid, r] of Object.entries(rankings)) {
    insRanking.run(uid, r.title ?? null, r.visibility ?? "friends", new Date("2026-08-10T18:00:00-04:00").toISOString());
    let list: string[] = [];
    const t0 = new Date("2026-08-10T18:00:00-04:00").getTime() - r.arrival.length * 3 * 86400_000;
    r.arrival.forEach((shopId, i) => {
      const already = new Set(list);
      const targetIndex = r.final.filter((s) => already.has(s) || s === shopId).indexOf(shopId);
      const replay = replayInsertion(shopId, list, targetIndex);
      const when = new Date(t0 + i * 3 * 86400_000);
      replay.comparisons.forEach((c, j) => {
        insCmp.run(
          `c_${uid}_${i}_${j}`, uid, c.winner, c.loser, "insertion",
          new Date(when.getTime() + j * 4000).toISOString(),
        );
        cmpCount++;
      });
      list = replay.list;
    });
    if (JSON.stringify(list) !== JSON.stringify(r.final)) fail(`replay mismatch for ${uid}`);
    list.forEach((shopId, idx) => {
      const arrivalIdx = r.arrival.indexOf(shopId);
      insEntry.run(uid, shopId, idx + 1, new Date(t0 + arrivalIdx * 3 * 86400_000).toISOString());
    });
  }

  const insList = db.prepare(
    "INSERT INTO lists (id, owner_id, title, is_collaborative, visibility, created_at) VALUES (?,?,?,?,?,?)",
  );
  const insItem = db.prepare(
    "INSERT INTO list_items (list_id, shop_id, position, added_by, note, added_at) VALUES (?,?,?,?,?,?)",
  );
  const insEditor = db.prepare("INSERT INTO list_editors (list_id, user_id, added_at) VALUES (?,?,?)");
  for (const l of lists) {
    insList.run(l.id, l.owner_id, l.title, l.is_collaborative ? 1 : 0, l.visibility, l.created_at);
    l.editors.forEach((e) => insEditor.run(l.id, e, l.created_at));
    l.items.forEach((it, i) => insItem.run(l.id, it.shop_id, i + 1, it.added_by, it.note ?? null, l.created_at));
  }

  const insFr = db.prepare(
    "INSERT INTO friendships (id, user_id, friend_id, status, created_at, responded_at) VALUES (?,?,?,?,?,?)",
  );
  friendships.forEach((f, i) =>
    insFr.run(`f_${i}`, f.user_id, f.friend_id, f.status, f.created_at, f.responded_at),
  );

  const insTok = db.prepare(
    "INSERT INTO share_tokens (token, kind, user_id, list_id, created_at, revoked_at) VALUES (?,?,?,?,?,?)",
  );
  for (const t of tokens) insTok.run(t.token, t.kind, t.user_id, t.list_id ?? null, t.created_at, t.revoked_at);

  // ── analytics: derived deterministically ──
  // Every log implies an app_open + log_created at that moment. Then the
  // north-star cohort: for users with zero logs in the week of 2026-08-03,
  // add app_opens on two distinct days that week (returned, logged nothing).
  const insEv = db.prepare(
    "INSERT INTO analytics_events (user_id, event, props_json, created_at) VALUES (?,?,?,?)",
  );
  for (const lg of logs) {
    insEv.run(lg.user_id, "app_open", "{}", lg.created_at);
    insEv.run(lg.user_id, "log_created", JSON.stringify({ shop_id: lg.shop_id }), lg.created_at);
  }
  const QUIET_WEEK_START = new Date("2026-08-03T00:00:00-04:00");
  const QUIET_WEEK_END = new Date("2026-08-10T00:00:00-04:00");
  const loggedThatWeek = new Set(
    logs
      .filter((lg) => {
        const t = new Date(lg.created_at);
        return t >= QUIET_WEEK_START && t < QUIET_WEEK_END;
      })
      .map((lg) => lg.user_id),
  );
  let northStarSeeded = 0;
  for (const u of users) {
    if (loggedThatWeek.has(u.id)) continue;
    if (new Date(u.created_at) > QUIET_WEEK_END) continue; // not yet signed up
    insEv.run(u.id, "app_open", "{}", "2026-08-04T12:10:00-04:00");
    insEv.run(u.id, "app_open", "{}", "2026-08-06T19:45:00-04:00");
    northStarSeeded++;
  }
  for (let i = 0; i < 6; i++) {
    insEv.run(null, "share_viewed", JSON.stringify({ token: "maya-ranks-campus-coffee" }), `2026-08-0${i + 4}T21:00:00-04:00`);
  }

  db.exec("COMMIT");

  const count = (sql: string) => (db.prepare(sql).get() as { n: number }).n;
  console.log(`seeded ${dbPath}`);
  console.log(`  shops=${count("SELECT count(*) n FROM shops")} users=${count("SELECT count(*) n FROM users")} logs=${count("SELECT count(*) n FROM logs")}`);
  console.log(`  comparisons=${cmpCount} ranking_entries=${count("SELECT count(*) n FROM ranking_entries")} lists=${count("SELECT count(*) n FROM lists")}`);
  console.log(`  friendships=${count("SELECT count(*) n FROM friendships")} tokens=${count("SELECT count(*) n FROM share_tokens")} events=${count("SELECT count(*) n FROM analytics_events")}`);
  console.log(`  north-star quiet-week users seeded=${northStarSeeded}`);
  db.close();
}

// Run directly (npm run seed)
if (process.argv[1] && process.argv[1].replace(/\\/g, "/").endsWith("server/db/seed.ts")) {
  runSeed();
}
